version: "3"
services:
  app:
    restart: always
    build: .
    env_file:
      - variables.env
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo:3.1
    ports:
      - "27017:27017"
