version: "3"
services:
  app:
    restart: always
    build: .
    env_file:
      - variables.env
    ports:
      - 3001:3001
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: weather
    volumes:
      - data-volume:/var/lib/db
    ports:
      - 5432:5432
volumes:
  data-volume:
    driver: local
